<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use App\Models\Store;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class DaliCatalogSeeder extends Seeder
{
    public function run(): void
    {
        $categories = collect([
            'Meat',
            'Dairy & Eggs',
            'Vegetables & Fruits',
            'Snacks',
            'Packed Foods',
        ])->mapWithKeys(function (string $name): array {
            $category = Category::query()->firstOrCreate(
                ['slug' => Str::slug($name)],
                ['name' => $name],
            );

            return [$name => $category];
        });

        foreach ($this->stores() as $storeData) {
            $store = Store::query()->updateOrCreate(
                ['slug' => Str::slug($storeData['name'])],
                [
                    'name' => $storeData['name'],
                    'description' => $storeData['description'],
                    'address' => 'Cordova, Cebu, Philippines',
                    'latitude' => $storeData['latitude'],
                    'longitude' => $storeData['longitude'],
                    'is_active' => true,
                ],
            );

            $this->seedDeliveryOptions($store);

            foreach ($storeData['products'] as $categoryName => $productNames) {
                $category = $categories->get($categoryName);

                foreach (array_unique($productNames) as $productName) {
                    Product::query()->updateOrCreate(
                        [
                            'store_id' => $store->id,
                            'name' => $productName,
                        ],
                        [
                            'category_id' => $category->id,
                            'description' => "{$productName} from {$store->name}.",
                            'price' => $this->priceFor($productName, $categoryName),
                            'stock_quantity' => 50,
                            'unit' => $this->unitFor($productName, $categoryName),
                            'is_available' => true,
                        ],
                    );
                }
            }
        }
    }

    /**
     * @return array<int, array{
     *     name: string,
     *     description: string,
     *     latitude: float,
     *     longitude: float,
     *     products: array<string, array<int, string>>
     * }>
     */
    private function stores(): array
    {
        return [
            [
                'name' => "Enjo's Meatshop",
                'description' => 'Fresh beef, pork, and chicken supplier.',
                'latitude' => 10.2624,
                'longitude' => 123.9531,
                'products' => [
                    'Meat' => [
                        'Beef Chuck',
                        'Ground Beef',
                        'Ground Pork',
                        'Pork Belly',
                        'Chicken Wings',
                        'Whole Chicken',
                    ],
                ],
            ],
            [
                'name' => 'Co-Op Meatshop',
                'description' => 'Meat and processed meat supplier.',
                'latitude' => 10.2468,
                'longitude' => 123.9462,
                'products' => [
                    'Meat' => [
                        'Pork Feet',
                        'Whole Chicken',
                        'Chicken Nuggets',
                        'Hotdogs',
                        'Corned Beef',
                        'Luncheon Meat',
                        'Chorizo',
                    ],
                ],
            ],
            [
                'name' => 'Nuñez Meat Food and Supply',
                'description' => 'Fresh meat, fish, and processed meat supplier.',
                'latitude' => 10.2851,
                'longitude' => 123.9617,
                'products' => [
                    'Meat' => [
                        'Pork Belly',
                        'Chicken Feet',
                        'Whole Chicken',
                        'Bangus',
                        'Pork Ham',
                        'Tocino',
                        'Longganisa',
                    ],
                ],
            ],
            [
                'name' => 'Mangnolia',
                'description' => 'Chicken and dairy products supplier.',
                'latitude' => 10.3152,
                'longitude' => 123.9365,
                'products' => [
                    'Meat' => [
                        'Chicken Wings',
                        'Chicken Thigh',
                        'Drumsticks',
                        'Chicken Liver',
                    ],
                    'Dairy & Eggs' => [
                        'Eggs',
                        'Chicken Eggs',
                        'Cheese',
                        'Cheddar Cheese',
                        'Processed Cheese',
                        'Yogurt',
                        'Strawberry Yogurt',
                        'Mango Yogurt',
                        'Whipping Cream',
                        'Sour Cream',
                        'Fresh Milk',
                        'Butter',
                        'Chocolate Milk',
                    ],
                ],
            ],
            [
                'name' => "Tina's Fish & Seafood Supply",
                'description' => 'Fresh fish and seafood supplier.',
                'latitude' => 10.2415,
                'longitude' => 123.9448,
                'products' => [
                    'Meat' => [
                        'Rabbit Fish (Danggit)',
                        'Bangus',
                        'Tamban',
                        'Tilapia',
                        'Anchovies',
                        'Pompano Fish',
                        'Parrot Fish',
                        'Shrimp',
                        'Crab',
                        'Octopus',
                        'Squid',
                    ],
                ],
            ],
            [
                'name' => 'Cordova Federation of Dairy Cooperatives',
                'description' => 'Dairy and fresh egg cooperative.',
                'latitude' => 10.2528,
                'longitude' => 123.9512,
                'products' => [
                    'Dairy & Eggs' => [
                        'Fresh Eggs',
                        'Chicken Eggs',
                        'Brown Eggs',
                        'Cheese',
                        'Cheddar Cheese',
                        'Mozzarella Cheese',
                        'Cream Cheese',
                        'Yogurt',
                        'Plain Yogurt',
                        'Greek Yogurt',
                        'Strawberry Yogurt',
                        'Whipping Cream',
                        'All-Purpose Cream',
                        'Sour Cream',
                        'Fresh Milk',
                        'Butter',
                        'Chocolate Milk',
                    ],
                ],
            ],
            [
                'name' => 'Eggcelsius Cordova - Fresh Farm Eggs',
                'description' => 'Fresh farm egg supplier.',
                'latitude' => 10.2647,
                'longitude' => 123.9574,
                'products' => [
                    'Dairy & Eggs' => [
                        'Fresh Eggs',
                        'Chicken Eggs',
                        'Brown Eggs',
                        'Organic Eggs',
                        'Quail Eggs',
                        'Duck Eggs',
                        'Salted Eggs',
                    ],
                ],
            ],
            [
                'name' => 'Sunrise Milk & Egg Supply',
                'description' => 'Milk, butter, and egg supplier.',
                'latitude' => 10.2719,
                'longitude' => 123.9398,
                'products' => [
                    'Dairy & Eggs' => [
                        'Fresh Eggs',
                        'Chicken Eggs',
                        'Quail Eggs',
                        'Duck Eggs',
                        'Fresh Milk',
                        'Butter',
                        'Condensed Milk',
                        'Evaporated Milk',
                    ],
                ],
            ],
            [
                'name' => "Nanay Lita's Dairy Store",
                'description' => 'Dairy products and eggs supplier.',
                'latitude' => 10.2583,
                'longitude' => 123.9651,
                'products' => [
                    'Dairy & Eggs' => [
                        'Eggs',
                        'Fresh Eggs',
                        'Salted Eggs',
                        'Cheese',
                        'Cheddar Cheese',
                        'Cream Cheese',
                        'Yogurt',
                        'Mango Yogurt',
                        'Strawberry Yogurt',
                        'All-Purpose Cream',
                        'Whipping Cream',
                        'Fresh Milk',
                        'Butter',
                        'Condensed Milk',
                        'Evaporated Milk',
                    ],
                ],
            ],
            [
                'name' => 'Cordova Fresh Dairy Supply',
                'description' => 'Dairy products supplier.',
                'latitude' => 10.2754,
                'longitude' => 123.9487,
                'products' => [
                    'Dairy & Eggs' => [
                        'Cheese',
                        'Cheddar Cheese',
                        'Mozzarella Cheese',
                        'Cream Cheese',
                        'Yogurt',
                        'Greek Yogurt',
                        'Plain Yogurt',
                        'All-Purpose Cream',
                        'Whipping Cream',
                        'Fresh Milk',
                        'Butter',
                        'Evaporated Milk',
                    ],
                ],
            ],
            [
                'name' => 'Little Farm Dairy Shop',
                'description' => 'Dairy products supplier.',
                'latitude' => 10.2872,
                'longitude' => 123.9568,
                'products' => [
                    'Dairy & Eggs' => [
                        'Cheese',
                        'Cheddar Cheese',
                        'Processed Cheese',
                        'Yogurt',
                        'Strawberry Yogurt',
                        'Blueberry Yogurt',
                        'All-Purpose Cream',
                        'Whipping Cream',
                        'Sour Cream',
                    ],
                ],
            ],
            [
                'name' => 'Cebu Milkbar Supplier',
                'description' => 'Milk, yogurt, and dairy products supplier.',
                'latitude' => 10.3187,
                'longitude' => 123.9254,
                'products' => [
                    'Dairy & Eggs' => [
                        'Yogurt',
                        'Plain Yogurt',
                        'Strawberry Yogurt',
                        'Mango Yogurt',
                        'All-Purpose Cream',
                        'Whipping Cream',
                        'Fresh Milk',
                        'Butter',
                        'Chocolate Milk',
                        'Strawberry Milk',
                        'Condensed Milk',
                        'Evaporated Milk',
                    ],
                ],
            ],
            [
                'name' => "Angelito's Fruits and Vegies",
                'description' => 'Fresh vegetables and fruit supplier.',
                'latitude' => 10.2569,
                'longitude' => 123.9471,
                'products' => [
                    'Vegetables & Fruits' => [
                        'Cabbage',
                        'Carrots',
                        'Onion',
                        'Chilli',
                        'Bell Pepper',
                        'Apple',
                        'Watermelon',
                        'Pineapple',
                        'Lettuce',
                        'Spinach',
                        'Strawberry',
                        'Blueberry',
                        'Orange',
                        'Lemon',
                        'Calamansi',
                        'Potato',
                        'Sweet Potato',
                        'Radish',
                        'Banana',
                        'Mango',
                    ],
                ],
            ],
            [
                'name' => "John Lou's Fruit and Vegetable Trading",
                'description' => 'Fresh vegetables and fruit trading supplier.',
                'latitude' => 10.3026,
                'longitude' => 123.9298,
                'products' => [
                    'Vegetables & Fruits' => [
                        'Eggplant',
                        'Okra',
                        'Bokchoy',
                        'Kangkong',
                        'Pechay',
                        'Lanzones',
                        'Rambutan',
                        'Banana',
                        'Watermelon',
                        'Malunggay',
                        'Lettuce',
                        'Strawberry',
                        'Raspberry',
                        'Blueberry',
                        'Lemon',
                        'Orange',
                        'Calamansi',
                        'Pomelo',
                        'Carrots',
                        'Potato',
                        'Cassava',
                        'Ginger',
                        'Radish',
                        'Mango',
                        'Papaya',
                    ],
                ],
            ],
            [
                'name' => 'CJ Fruits',
                'description' => 'Fresh fruits and vegetables supplier.',
                'latitude' => 10.3238,
                'longitude' => 123.9147,
                'products' => [
                    'Vegetables & Fruits' => [
                        'Carrots',
                        'Cabbage',
                        'Bell Pepper',
                        'Eggplant',
                        'Apple',
                        'Banana',
                        'Pineapple',
                        'Grapes',
                        'Kiwi',
                        'Lettuce',
                        'Spinach',
                        'Pechay',
                        'Strawberry',
                        'Raspberry',
                        'Blueberry',
                        'Blackberry',
                        'Orange',
                        'Ponkan',
                        'Lime',
                        'Lemon',
                        'Potato',
                        'Sweet Potato',
                        'Mango',
                    ],
                ],
            ],
            [
                'name' => "Bheb's Fruits and Vegetables Supplier",
                'description' => 'Fresh fruits and vegetables supplier.',
                'latitude' => 10.2935,
                'longitude' => 123.9589,
                'products' => [
                    'Vegetables & Fruits' => [
                        'Carrots',
                        'Chilli',
                        'Bell Pepper',
                        'Tomato',
                        'Cucumber',
                        'Eggplant',
                        'Cherry',
                        'Avocado',
                        'Rambutan',
                        'Dragon Fruit',
                        'Mango',
                        'Malunggay',
                        'Kangkong',
                        'Pechay',
                        'Spinach',
                        'Strawberry',
                        'Raspberry',
                        'Blueberry',
                        'Orange',
                        'Lemon',
                        'Calamansi',
                        'Pomelo',
                        'Ponkan',
                        'Potato',
                        'Ginger',
                        'Cassava',
                        'Radish',
                        'Taro',
                        'Papaya',
                        'Pineapple',
                    ],
                ],
            ],
            [
                'name' => "James'nBro",
                'description' => 'Snacks and sweets supplier.',
                'latitude' => 10.3304,
                'longitude' => 123.9178,
                'products' => [
                    'Snacks' => [
                        'Chippy',
                        'Piattos',
                        'V-Cut',
                        'Potato Chips',
                        'Cheese Rings',
                        'Choco Knots',
                        'Berry Knots',
                        'Crackers',
                        'Butter Cookies',
                        'Choco Pretzels',
                        'Chocolate Bars',
                        'Chocolate Wafers',
                        'Gummy Candies',
                        'Fruit Chews',
                        'Mint Candies',
                        'Jelly Beans',
                        'Roasted Peanuts',
                        'Salted Peanuts',
                        'Pumpkin Seeds',
                        'Butter Popcorn',
                        'Cheese Popcorn',
                        'Caramel Popcorn',
                    ],
                ],
            ],
            [
                'name' => 'Bhebiesco',
                'description' => 'Snacks and sweets supplier.',
                'latitude' => 10.3091,
                'longitude' => 123.9376,
                'products' => [
                    'Snacks' => [
                        'Potato Chips',
                        'Cheese Chips',
                        'Corn Chips',
                        'Tortilla Chips',
                        'Crackers',
                        'Hansel',
                        'Hansel Crackers',
                        'Cream Crackers',
                        'Chocolate Cookies',
                        'Choco Mucho',
                        'Chocolate Bars',
                        'Chocolate Wafers',
                        'Hard Candies',
                        'Gummy Candies',
                        'Lollipops',
                        'Roasted Peanuts',
                        'Cashew Nuts',
                        'Sunflower Seeds',
                        'Mixed Nuts',
                        'Cheese Popcorn',
                        'Caramel Popcorn',
                    ],
                ],
            ],
            [
                'name' => 'M.Y San',
                'description' => 'Biscuits, snacks, and sweets supplier.',
                'latitude' => 10.3165,
                'longitude' => 123.9058,
                'products' => [
                    'Snacks' => [
                        'Potato Chips',
                        'Corn Chips',
                        'Cheese Rings',
                        'Fita',
                        'Grahams',
                        'Butter Cookies',
                        'Marie Biscuits',
                        'Chocolate Chip Cookies',
                        'Cream Biscuits',
                        'Chocolate Bars',
                        'Chocolate Wafers',
                        'Fruit Candies',
                        'Milk Candies',
                        'Gummy Candies',
                        'Mint Candies',
                        'Caramel Candies',
                        'Peanuts',
                        'Cashew Nuts',
                        'Butter Popcorn',
                        'Caramel Popcorn',
                        'Chocolate Popcorn',
                        'Cheese Popcorn',
                    ],
                ],
            ],
            [
                'name' => "Missin'u",
                'description' => 'Canned goods, noodles, pasta, and cereals supplier.',
                'latitude' => 10.2608,
                'longitude' => 123.9442,
                'products' => [
                    'Packed Foods' => [
                        'Canned Tuna',
                        'Canned Sardines',
                        'Canned Corn',
                        'Canned Meat',
                        'Cup Noodles',
                        'Instant Noodles',
                        'Instant Ramen',
                        'Chicken Noodles',
                        'Spaghetti',
                        'Macaroni',
                        'Instant Pasta',
                        'Corn Flakes',
                        'Chocolate Cereal',
                        'Honey Cereal',
                    ],
                ],
            ],
            [
                'name' => 'CBD Supply',
                'description' => 'Packed food and grocery supplier.',
                'latitude' => 10.3341,
                'longitude' => 123.9286,
                'products' => [
                    'Packed Foods' => [
                        'Corned Beef',
                        'Canned Tuna',
                        'Canned Sardines',
                        'Canned Mushrooms',
                        'Canned Tomato Sauce',
                        'Ho-mies Instant Noodles',
                        'Beef Instant Noodles',
                        'Spicy Instant Noodles',
                        'Cup Noodles',
                        'WOW Pasta',
                        'Spaghetti',
                        'Macaroni',
                        'Penne Pasta',
                        'Carbonara Pasta',
                        'Ganador Rice',
                        'Dinorado Rice',
                        'Sinandomeng Rice',
                        'Brown Rice',
                        'Corn Flakes',
                        'Oat Cereal',
                        'Chocolate Cereal',
                        'Granola',
                        'Honey Cereal',
                    ],
                ],
            ],
            [
                'name' => 'Puregoods Ready-to-Eat',
                'description' => 'Canned goods and ready-to-eat meals supplier.',
                'latitude' => 10.2786,
                'longitude' => 123.9518,
                'products' => [
                    'Packed Foods' => [
                        'Canned Beef',
                        'Canned Pork',
                        'Canned Sardines',
                        'Kare-Kare',
                        'Lechon Paksiw',
                        'Bicol Express',
                        'Bistek Tagalog',
                        'Adobo',
                        'Chicken Afritada',
                    ],
                ],
            ],
            [
                'name' => 'Premium Food Supply',
                'description' => 'Packed food, rice, pasta, and ready-meal supplier.',
                'latitude' => 10.3412,
                'longitude' => 123.9005,
                'products' => [
                    'Packed Foods' => [
                        'Canned Tuna',
                        'Corned Beef',
                        'Canned Sardines',
                        'Canned Beans',
                        'Canned Fruit Cocktail',
                        'Canned Mushrooms',
                        'Spaghetti',
                        'Fettuccine',
                        'Penne Pasta',
                        'Elbow Macaroni',
                        'Lasagna Sheets',
                        'Ganador Rice',
                        'Lion Ivory',
                        'Rose Gold',
                        'Dinorado',
                        'Sinandomeng',
                        'Jasmine Rice',
                        'Brown Rice',
                        'Corn Flakes',
                        'Granola',
                        'Bran Cereal',
                        'Chocolate Cereal',
                        'Beef Caldereta',
                        'Bistek Tagalog',
                        'Chicken Afritada',
                        'Pork Adobo',
                        'Beef Mechado',
                        'Giniling',
                    ],
                ],
            ],
            [
                'name' => 'Puregoods Food Distributors',
                'description' => 'Noodles and cereal supplier.',
                'latitude' => 10.3501,
                'longitude' => 123.9183,
                'products' => [
                    'Packed Foods' => [
                        'Instant Ramen',
                        'Cup Noodles',
                        'Seafood Instant Noodles',
                        'Chicken Instant Noodles',
                        'Spicy Ramen',
                        'Oatmeal Cereal',
                        'Corn Flakes',
                        'Fruit Granola',
                        'Honey Cereal',
                        'Rice Cereal',
                        'Chocolate Cereal',
                    ],
                ],
            ],
            [
                'name' => 'Cordova Food Supply',
                'description' => 'Instant noodle and grocery supplier.',
                'latitude' => 10.2694,
                'longitude' => 123.9561,
                'products' => [
                    'Packed Foods' => [
                        'Instant Noodles',
                        'Cup Noodles',
                        'Beef Ramen',
                    ],
                ],
            ],
            [
                'name' => 'Cordova Rice Trading',
                'description' => 'Rice supplier.',
                'latitude' => 10.2849,
                'longitude' => 123.9435,
                'products' => [
                    'Packed Foods' => [
                        'Jasmine Rice',
                        'Dinorado Rice',
                        'Sinandomeng Rice',
                        'Premium White Rice',
                        'Brown Rice',
                        'Sticky Rice',
                    ],
                ],
            ],
            [
                'name' => 'Cordova Food Distributors',
                'description' => 'Pasta and grocery supplier.',
                'latitude' => 10.3287,
                'longitude' => 123.9126,
                'products' => [
                    'Packed Foods' => [
                        'Spaghetti',
                        'Macaroni',
                        'Fusilli',
                        'Linguine',
                    ],
                ],
            ],
            [
                'name' => 'Cordova Ready Meals Supply',
                'description' => 'Ready-to-eat Filipino meal supplier.',
                'latitude' => 10.2958,
                'longitude' => 123.9506,
                'products' => [
                    'Packed Foods' => [
                        'Kare-Kare',
                        'Bicol Express',
                        'Chicken Adobo',
                        'Pork Menudo',
                        'Beef Mechado',
                    ],
                ],
            ],
        ];
    }

    private function priceFor(string $productName, string $categoryName): float
    {
        $prices = [
            'Beef Chuck' => 420.00,
            'Ground Beef' => 390.00,
            'Ground Pork' => 350.00,
            'Pork Belly' => 380.00,
            'Pork Feet' => 180.00,
            'Chicken Wings' => 250.00,
            'Whole Chicken' => 220.00,
            'Chicken Feet' => 120.00,
            'Chicken Thigh' => 240.00,
            'Drumsticks' => 230.00,
            'Chicken Liver' => 150.00,
            'Bangus' => 220.00,
            'Rabbit Fish (Danggit)' => 260.00,
            'Tamban' => 180.00,
            'Tilapia' => 190.00,
            'Anchovies' => 160.00,
            'Pompano Fish' => 320.00,
            'Parrot Fish' => 350.00,
            'Shrimp' => 450.00,
            'Crab' => 500.00,
            'Octopus' => 380.00,
            'Squid' => 350.00,
            'Pork Ham' => 180.00,
            'Tocino' => 160.00,
            'Longganisa' => 150.00,
            'Chicken Nuggets' => 120.00,
            'Hotdogs' => 110.00,
            'Corned Beef' => 75.00,
            'Luncheon Meat' => 85.00,
            'Chorizo' => 120.00,

            'Fresh Eggs' => 120.00,
            'Chicken Eggs' => 110.00,
            'Brown Eggs' => 125.00,
            'Organic Eggs' => 160.00,
            'Quail Eggs' => 55.00,
            'Duck Eggs' => 90.00,
            'Salted Eggs' => 85.00,
            'Eggs' => 110.00,
            'Cheese' => 130.00,
            'Cheddar Cheese' => 150.00,
            'Mozzarella Cheese' => 170.00,
            'Cream Cheese' => 160.00,
            'Processed Cheese' => 120.00,
            'Yogurt' => 65.00,
            'Plain Yogurt' => 70.00,
            'Greek Yogurt' => 95.00,
            'Strawberry Yogurt' => 75.00,
            'Mango Yogurt' => 75.00,
            'Blueberry Yogurt' => 80.00,
            'Whipping Cream' => 130.00,
            'All-Purpose Cream' => 95.00,
            'Sour Cream' => 110.00,
            'Fresh Milk' => 100.00,
            'Butter' => 120.00,
            'Chocolate Milk' => 55.00,
            'Strawberry Milk' => 55.00,
            'Condensed Milk' => 65.00,
            'Evaporated Milk' => 55.00,

            'Apple' => 180.00,
            'Watermelon' => 55.00,
            'Pineapple' => 75.00,
            'Banana' => 85.00,
            'Mango' => 160.00,
            'Grapes' => 280.00,
            'Kiwi' => 300.00,
            'Strawberry' => 180.00,
            'Raspberry' => 220.00,
            'Blueberry' => 220.00,
            'Blackberry' => 230.00,
            'Cherry' => 350.00,
            'Avocado' => 180.00,
            'Dragon Fruit' => 160.00,
            'Lanzones' => 140.00,
            'Rambutan' => 130.00,
            'Papaya' => 65.00,
            'Orange' => 150.00,
            'Lemon' => 160.00,
            'Calamansi' => 80.00,
            'Pomelo' => 130.00,
            'Ponkan' => 120.00,
            'Lime' => 120.00,
            'Cabbage' => 70.00,
            'Carrots' => 95.00,
            'Onion' => 120.00,
            'Chilli' => 180.00,
            'Bell Pepper' => 190.00,
            'Eggplant' => 80.00,
            'Okra' => 100.00,
            'Bokchoy' => 75.00,
            'Kangkong' => 45.00,
            'Pechay' => 60.00,
            'Lettuce' => 140.00,
            'Spinach' => 120.00,
            'Malunggay' => 50.00,
            'Tomato' => 90.00,
            'Cucumber' => 75.00,
            'Potato' => 100.00,
            'Sweet Potato' => 90.00,
            'Radish' => 70.00,
            'Cassava' => 65.00,
            'Ginger' => 160.00,
            'Taro' => 80.00,

            'Kare-Kare' => 230.00,
            'Lechon Paksiw' => 220.00,
            'Bicol Express' => 200.00,
            'Bistek Tagalog' => 220.00,
            'Adobo' => 180.00,
            'Chicken Afritada' => 190.00,
            'Beef Caldereta' => 240.00,
            'Pork Adobo' => 190.00,
            'Beef Mechado' => 240.00,
            'Giniling' => 180.00,
            'Chicken Adobo' => 180.00,
            'Pork Menudo' => 190.00,
        ];

        if (array_key_exists($productName, $prices)) {
            return $prices[$productName];
        }

        return match ($categoryName) {
            'Snacks' => 55.00,
            'Packed Foods' => 65.00,
            default => 100.00,
        };
    }

    private function unitFor(string $productName, string $categoryName): string
    {
        $dozenProducts = [
            'Fresh Eggs',
            'Chicken Eggs',
            'Brown Eggs',
            'Organic Eggs',
            'Quail Eggs',
            'Duck Eggs',
            'Salted Eggs',
            'Eggs',
        ];

        $kilogramProducts = [
            'Beef Chuck',
            'Ground Beef',
            'Ground Pork',
            'Pork Belly',
            'Pork Feet',
            'Chicken Wings',
            'Whole Chicken',
            'Chicken Feet',
            'Chicken Thigh',
            'Drumsticks',
            'Chicken Liver',
            'Bangus',
            'Rabbit Fish (Danggit)',
            'Tamban',
            'Tilapia',
            'Anchovies',
            'Pompano Fish',
            'Parrot Fish',
            'Shrimp',
            'Crab',
            'Octopus',
            'Squid',
            'Apple',
            'Watermelon',
            'Pineapple',
            'Banana',
            'Mango',
            'Grapes',
            'Lanzones',
            'Rambutan',
            'Orange',
            'Lemon',
            'Calamansi',
            'Pomelo',
            'Ponkan',
            'Lime',
            'Cabbage',
            'Carrots',
            'Onion',
            'Chilli',
            'Bell Pepper',
            'Eggplant',
            'Okra',
            'Bokchoy',
            'Kangkong',
            'Pechay',
            'Lettuce',
            'Spinach',
            'Malunggay',
            'Tomato',
            'Cucumber',
            'Potato',
            'Sweet Potato',
            'Radish',
            'Cassava',
            'Ginger',
            'Taro',
            'Ganador Rice',
            'Dinorado Rice',
            'Sinandomeng Rice',
            'Brown Rice',
            'Jasmine Rice',
            'Premium White Rice',
            'Sticky Rice',
            'Dinorado',
            'Sinandomeng',
        ];

        $packProducts = [
            'Strawberry',
            'Raspberry',
            'Blueberry',
            'Blackberry',
            'Cherry',
            'Kiwi',
        ];

        if (in_array($productName, $dozenProducts, true)) {
            return 'dozen';
        }

        if (in_array($productName, $kilogramProducts, true)) {
            return 'kg';
        }

        if (in_array($productName, $packProducts, true)) {
            return 'pack';
        }

        return match ($categoryName) {
            'Snacks' => 'pack',
            default => 'piece',
        };
    }

    private function seedDeliveryOptions(Store $store): void
    {
        $options = [
            [
                'name' => \App\Enums\DeliveryOptionName::Saver,
                'description' => 'Lowest-cost delivery option.',
                'additional_fee' => 0.00,
                'estimated_delivery_minutes' => 90,
            ],
            [
                'name' => \App\Enums\DeliveryOptionName::Standard,
                'description' => 'Balanced delivery speed and price.',
                'additional_fee' => 25.00,
                'estimated_delivery_minutes' => 60,
            ],
            [
                'name' => \App\Enums\DeliveryOptionName::Express,
                'description' => 'Fastest delivery option.',
                'additional_fee' => 50.00,
                'estimated_delivery_minutes' => 30,
            ],
        ];

        foreach ($options as $option) {
            $store->deliveryOptions()->updateOrCreate(
                ['name' => $option['name']],
                [
                    ...$option,
                    'is_active' => true,
                ],
            );
        }
    }
}
